export const INGREDIENTS = [
  {
    name: "Chicken Breast",
    fat: 3.6,
    carbohydrate: 0.1,
    protein: 31,
    calories: 165,
  },
  {
    name: "Chicken Thighs",
    fat: 8,
    carbohydrate: 0.1,
    protein: 24,
    calories: 177,
  },
  {
    name: "Ribeye Steak",
    fat: 22,
    carbohydrate: 0.1,
    protein: 24,
    calories: 291,
  },
  {
    name: "Wheat Flour",
    fat: 1,
    carbohydrate: 76,
    protein: 10,
    calories: 364,
  },
  {
    name: "Potato",
    fat: 0.1,
    carbohydrate: 21,
    protein: 2.5,
    calories: 93,
  },
  {
    name: "Olive Oil",
    fat: 100,
    carbohydrate: 0,
    protein: 0,
    calories: 884,
  },
  {
    name: "Onion",
    fat: 0.1,
    carbohydrate: 9,
    protein: 1.1,
    calories: 40,
  },
  {
    name: "Bell Pepper",
    fat: 0.1,
    carbohydrate: 4.6,
    protein: 0.9,
    calories: 20,
  },
  {
    name: "Garlic",
    fat: 0.5,
    carbohydrate: 33,
    protein: 6.4,
    calories: 149,
  },
  {
    name: "Lentil",
    fat: 1.1,
    carbohydrate: 63,
    protein: 25,
    calories: 352,
  },
  {
    name: "Carrot",
    fat: 0.2,
    carbohydrate: 9.6,
    protein: 0.9,
    calories: 41,
  },
  {
    name: "White Rice",
    fat: 0.6,
    carbohydrate: 79,
    protein: 6.6,
    calories: 360,
  },
  {
    name: "Egg",
    fat: 9.5,
    carbohydrate: 0.7,
    protein: 13,
    calories: 143,
  },
];
